{{- if .Values.ingress.enabled -}}
{{- $fullName := include "charts.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.sha }}-{{ $fullName }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
       - {{ .Values.host }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: st-{{ .Values.sha }}-{{ include "charts.name" . }}-rails
              servicePort: 3000
          - path: /packs
            backend:
              serviceName: st-{{ .Values.sha }}-{{ include "charts.name" . }}-static
              servicePort: 80
  {{- end }}
