# Default values for whois.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/internetee/whois
  pullPolicy: IfNotPresent
  # Reference to Pullrequest. Used for Staging deployments
  tag: 0000

# Image pulling secrets
imagePullSecrets: regcred-eisbot

nameOverride: ""
fullnameOverride: ""
# Rails environment name
environment: "staging"

service:
  # App container name
  name: whois

  # Service type
  type: ClusterIP

  # App service port
  port: 43

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

configmap:
    database: whois-database-config

app:
  status: "staging"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
