apiVersion: v1
kind: Service
metadata:
  name: st-{{ .Values.reference }}-{{ include "registry_epp.name" . }}
  labels:
    {{- include "registry_epp.labels" . | nindent 4 }}
    epp: epp
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.rails.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "registry_epp.selectorLabels" . | nindent 4 }}
    epp: epp
