{{- if .Values.ingress.enabled -}}
{{- $fullName := include "registry_epp.fullname" . -}}
{{- $svcPort := .Values.service.rails.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.reference }}-{{ $fullName }}
  labels:
    {{- include "registry_epp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
       - r{{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
  rules:
    - host: r{{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: st-{{ .Values.reference }}-{{ include "registry_epp.name" . }}
                port: 
                  number: {{ $svcPort }}
{{- end }}
