{{- if .Values.ingress.enabled -}}
{{- $fullName := include "accreditation-center.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if eq .Values.status "st" }}
  name: {{ .Values.reference }}-{{ $fullName }}
  {{- else }}
  name: "accreditation"
  {{- end }}
  labels:
    {{- include "accreditation-center.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        {{- if eq .Values.status "st" }}
        - {{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
        {{- else }}
        - {{ .Values.host }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    {{- if eq .Values.status "st" }}
    - host: {{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
    {{- else }}
    - host: {{ .Values.host }}
    {{- end }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                {{- if eq .Values.status "st" }}
                name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-rails
                {{- else }}
                name: {{ include "accreditation-center.name" . }}-rails
                {{- end }}
                port:
                  number: {{ $svcPort }}
          - pathType: Prefix
            path: /packs
            backend:
              service:
                {{- if eq .Values.status "st" }}
                name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-static
                {{- else }}
                name: {{ include "accreditation-center.name" . }}-static
                {{- end }}
                port:
                  number: 80
{{- end }}
