apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-rails
  labels:
    {{- include "accreditation-center.labels" . | nindent 4 }}
    accreditation: rails
spec:
  selector:
    matchLabels:
      {{- include "accreditation-center.selectorLabels" . | nindent 6 }}
      accreditation: rails
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "accreditation-center.selectorLabels" . | nindent 8 }}
        accreditation: rails
    spec:
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTIC_APM_SERVER_URL
              value: 'http://apm-server-apm-server.apm.svc.cluster.local:8200:'
            - name: APP_DBHOST
              value: {{ .Values.dbHost }}
            - name: RAILS_ENV
              value: {{ .Values.railsEnv }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: accreditation-key-base
                  key: SECRET_KEY_BASE
            - name: CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-pswd
                  key: password
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - bash
            - -c 
            - "bundle exec rails server -b 0.0.0.0"
          volumeMounts:
          - name: database-config
            mountPath: "/opt/webapps/app/config/database.yml"
            subPath: "database.yml"
          - name: bot-certs
            mountPath: "/opt/ca/certs/accr_bot.crt.pem"
            subPath: accr_bot.crt.pem
          - name: bot-certs
            mountPath: "/opt/ca/private/client.key"
            subPath: client.key
      imagePullSecrets:
       - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: database-config
          configMap: 
            name: {{ .Values.dbConfig }}
        - name: bot-certs
          secret:
            secretName: {{ .Values.bot.certificates }}
