apiVersion: v1
kind: Service
metadata:
  name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-registry
  labels:
    {{- include "accreditation-center.labels" . | nindent 4 }}
    accreditation: registry
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "accreditation-center.selectorLabels" . | nindent 4 }}
    accreditation: registry
