apiVersion: v1
kind: Service
metadata:
  name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-static
  labels:
    {{- include "accreditation-center.labels" . | nindent 4 }}
    accreditation: static
spec:
  type: {{ .Values.service.type }}
  ports:
     - port: 80
       targetPort: http
       protocol: TCP
       name: http
  selector:
    {{- include "accreditation-center.labels" . | nindent 4 }}
    accreditation: static
