apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if eq .Values.status "st" }}
  name: st-{{ .Values.reference }}-{{ include "accreditation-center.name" . }}-static
  {{- else }}
  name: {{ include "accreditation-center.name" . }}-static
  {{- end }}
  labels:
    {{- include "accreditation-center.labels" . | nindent 4 }}
    accreditation: static
spec:
  selector:
    matchLabels:
      {{- include "accreditation-center.labels" . | nindent 6 }}
      accreditation: static
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "accreditation-center.labels" . | nindent 8 }}
        accreditation: static
    spec:
      containers:
        - name: {{ .Chart.Name }}-static
          tty: true
          image: "{{ .Values.image.repository }}:STATIC_{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: default-conf
            mountPath: "/etc/nginx/conf.d/default.conf"
            subPath: "default.conf"
      imagePullSecrets:
       - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: default-conf
          configMap: 
            name: {{ .Values.staticConfig }}