apiVersion: v1
kind: Service
metadata:
  name: st-{{ .Values.reference }}-{{ include "registry.name" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.rails.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
