{{- if .Values.ingress.enabled -}}
{{- $fullName := include "charts.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.reference }}-{{ $fullName }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
       - {{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
      secretName: {{ .Values.secretName }}
  rules:
    - host: {{ .Values.nameOverride }}-{{ .Values.reference }}.{{ .Values.baseUrl }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: st-{{ .Values.reference }}-{{ include "charts.name" . }}
                port:
                  number: {{ $svcPort }}
  {{- end }}
